### ISSUE TITLE
Mention of `/gh_event` endpoint missing in README

### ISSUE THREAD

**Issue by stefanluptak** [cpanato/github_actions_exporter#1]
It took me some time to realize, that I have to point the GitHub webhook to the `/gh_event` route of the exporter. It would be useful to have it mentioned in the README.
Also, there's probably a mistake in the description of the `web.gh-webhook-path` option in the `main.go` file at the line `29`.

**Comment by cpanato** [comment]
thanks @stefanluptak, are you willing to open a PR to fix those things? otherwise I will do that when I get a free cycle

**Comment by stefanluptak** [comment]
OK, I'll try. :-) I thought about that, but then I realized, that maybe you will know better how to put the word in the README. But I'll try my best. :-)
