### ISSUE TITLE
Add a branch label to workflow metrics

### ISSUE THREAD

**Issue by kjkuan** [cpanato/github_actions_exporter#154]
Hi,

Would it make sense to add a `branch` label to the workflow metrics (`workflow_*`)?

Our github action workflow works for both PR branches and special environment branches like, `master`, `staging`, and `prod`. Having a `branch` label in the workflow metrics would help us distinguish different types of workflow metrics when computing statistics about github action workflows.

Thanks

**Comment by cpanato** [comment]
makes sense, are you willing to add a PR for that?

**Comment by kjkuan** [comment]
cool, my colleague has started working on it. We'll send a PR once it's ready, thanks!
