### ISSUE TITLE
Creating releases

### ISSUE THREAD

**Issue by janakerman-form3** [cpanato/github_actions_exporter#52]
@cpanato - there have been a few contributions to this repo since the last release. Would you mind creating a new release?

Perhaps longer term it would be worth updating the workflows to release from push to `master` with some form of automated versioning (e.g driven by [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)).

**Comment by cpanato** [comment]
thanks, i wil check if need to update other things and cut a release at the end of the week

releasing from every time from the main branch i dont like that much, but we can release a edge/latest tag for that

**Comment by janakerman-form3** [comment]
@cpanato - any update? :)

**Comment by cpanato** [comment]
i was at medical leave, getting back this week

**Comment by janakerman-form3** [comment]
Thanks. Hope you're all recovered!

**Comment by cpanato** [comment]
released https://github.com/cpanato/github_actions_exporter/releases/tag/v0.4.2
