### ISSUE TITLE
Create Helm Chart

### ISSUE THREAD

**Issue by bradmccoydev** [cpanato/github_actions_exporter#78]
It would be nice to have some Kubernetes manifest files for this project whether it is a helm chart or done in Kustomise.

I'm happy to make it if there is not one existing..

**Comment by cpanato** [comment]
@bradmccoydev thanks for the issue, i am working on a helm chart and testing that, that will be available soon :)

**Comment by cpanato** [comment]
but if you want to do one in Kustomise I will be happy to review the PR

**Comment by bradmccoydev** [comment]
Hey @cpanato how are you? I'm just checking up on the helm chart for this.. Thanks

**Comment by cpanato** [comment]
sorry for the long delay

helm chart is available

```
helm repo add cpanato http://cpanato.dev/github_actions_exporter/
```

`helm install --dry-run --debug test cpanato/github-exporter` for example

thanks!
